name: lint

on:
  pull_request:

jobs:
  check-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: install-dependencies
        run: yarn
      - name: lint
        run: yarn lint